/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liang_myapplication_KeyBoard */

#ifndef _Included_com_example_liang_myapplication_KeyBoard
#define _Included_com_example_liang_myapplication_KeyBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liang_myapplication_KeyBoard
 * Method:    Start_KeyBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_liang_myapplication_KeyBoard_Start_1KeyBoard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
